#pragma once

#ifndef IGNORE_WHEN_TESTING

#include <string>
#include <string_view>
#include <any>

#include <cprt.hpp>
#include <third_party/antlr4/antlr4-runtime.h>

#include "frontend/IRAddr.hpp"
#include "frontend/IRInstr.hpp"
#include "frontend/SysAntlr/SysYParser.h"
#include "frontend/SysAntlr/SysYBaseVisitor.h"
#include "frontend/SysAntlr/SysYVisitor.h"


namespace frontend {

/*  Visitor for AST generated by parser.
 * */
class ASTVisitor : public SysYBaseVisitor {
  protected:
	ircode::AddrPool addrPool;
	ircode::Scope * pScope;
	enum class BType {
		Float, Int, Error
	};
	
	struct Info {
		/*  inGlobal: is visitor processing statements on global field.
		 *  isGlobal is true at first, and becomes false when enter `FuncDef`, and
		 *  becomes true after leaving `FuncDef`.
		 * */
		bool inGlobal;
		/*  btype: basic type of decl var.
		 *  Changed when visiting BType.
		 * */
		BType btype;
		/*  isConst: is decl var constant.
		 *  Changed just after visiting ConstDecl/VarDecl.
		 * */
		bool isConst;
		/*  visitingConst: is calculating static value.
		 *  Changed just entering and leaving ConstExp. false in default.
		 * */
		bool visitingConst;
		
		Info() : inGlobal(true), btype(BType::Error), isConst(false),
		         visitingConst(false) {
		}
	} info;
	
	static BType strToBType(const std::string & str) {
		if (str == "float") {
			return BType::Float;
		} else if (str == "int") {
			return BType::Int;
		} else {
			com::Throw("Unknown BType[" + str + "]!", CODEPOS);
		}
	}
  
  public:
	ASTVisitor();
	
	//  Visit children, return: nullptr.
	std::any visitChildren(antlr4::tree::ParseTree * node) override;
	
	//  Just visit children, return: nullptr.
	std::any visitCompUnit(SysYParser::CompUnitContext * ctx) override;
	
	//  Just visit children, return: nullptr.
	std::any visitDecl(SysYParser::DeclContext * ctx) override;
	
	std::any visitConstDecl(SysYParser::ConstDeclContext * ctx) override;
	
	//  Visit BType, change info.btype according to ctx->getText()
	std::any visitBType(SysYParser::BTypeContext * ctx) override;
	
	std::any visitConstDef(SysYParser::ConstDefContext * ctx) override;
	
	std::any visitScalarConstInitVal(
			SysYParser::ScalarConstInitValContext * ctx
	) override;
	
	std::any
	visitListConstInitVal(SysYParser::ListConstInitValContext * ctx) override;
	
	std::any visitVarDecl(SysYParser::VarDeclContext * ctx) override;
	
	std::any visitUninitVarDef(SysYParser::UninitVarDefContext * ctx) override;
	
	std::any
	visitInitVarDef(SysYParser::InitVarDefContext * ctx) override;
	
	std::any
	visitScalarInitVal(SysYParser::ScalarInitValContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitListInitval(SysYParser::ListInitvalContext * ctx) override {
		return visitChildren(ctx);
	}
	
	std::any visitFuncDef(SysYParser::FuncDefContext * ctx) override;
	
	virtual std::any visitFuncType(SysYParser::FuncTypeContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitFuncFParams(SysYParser::FuncFParamsContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitFuncFParam(SysYParser::FuncFParamContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitBlock(SysYParser::BlockContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitBlockItem(SysYParser::BlockItemContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitAssignment(SysYParser::AssignmentContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitExpStmt(SysYParser::ExpStmtContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitBlockStmt(SysYParser::BlockStmtContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitIfStmt1(SysYParser::IfStmt1Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitIfStmt2(SysYParser::IfStmt2Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitWhileStmt(SysYParser::WhileStmtContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitBreakStmt(SysYParser::BreakStmtContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitContinueStmt(SysYParser::ContinueStmtContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitReturnStmt(SysYParser::ReturnStmtContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitExp(SysYParser::ExpContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitCond(SysYParser::CondContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitLVal(SysYParser::LValContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitPrimaryExp1(SysYParser::PrimaryExp1Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitPrimaryExp2(SysYParser::PrimaryExp2Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitPrimaryExp3(SysYParser::PrimaryExp3Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitNumber(SysYParser::NumberContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitUnary1(SysYParser::Unary1Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitUnary2(SysYParser::Unary2Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitUnary3(SysYParser::Unary3Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitUnaryOp(SysYParser::UnaryOpContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitFuncRParams(SysYParser::FuncRParamsContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitExpAsRParam(SysYParser::ExpAsRParamContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any
	visitStringAsRParam(SysYParser::StringAsRParamContext * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitMul2(SysYParser::Mul2Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitMul1(SysYParser::Mul1Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitAdd2(SysYParser::Add2Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitAdd1(SysYParser::Add1Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitRel2(SysYParser::Rel2Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitRel1(SysYParser::Rel1Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitEq1(SysYParser::Eq1Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitEq2(SysYParser::Eq2Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitLAnd2(SysYParser::LAnd2Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitLAnd1(SysYParser::LAnd1Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitLOr1(SysYParser::LOr1Context * ctx) override {
		return visitChildren(ctx);
	}
	
	virtual std::any visitLOr2(SysYParser::LOr2Context * ctx) override {
		return visitChildren(ctx);
	}
	
	//  Just visit AddExp. Return: ircode::StaticValue
	std::any visitConstExp(SysYParser::ConstExpContext * ctx) override;
};

}

#endif